export const sampleStats = [
  {
    label: "Years in business",
    labelBn: "ব্যবসার অভিজ্ঞতা",
    value: 8,
    prefix: null,
    suffix: "+",
    description: "Established presence supplying commercial installations across Bangladesh",
    descriptionBn: "সারা বাংলাদেশে বাণিজ্যিক প্রকল্পে সোলার ইকুইপমেন্ট সরবরাহের দীর্ঘ অভিজ্ঞতা",
    sortOrder: 1,
    isActive: true,
    isSample: true,
  },
  {
    label: "Projects supplied",
    labelBn: "সরবরাহকৃত প্রকল্প",
    value: 250,
    prefix: null,
    suffix: "+",
    description: "Industrial rooftops, commercial facilities, and rural telecom setups",
    descriptionBn: "শিল্প কারখানার ছাদ, বাণিজ্যিক প্রতিষ্ঠান ও টেলিকম টাওয়ার প্রকল্প",
    sortOrder: 2,
    isActive: true,
    isSample: true,
  },
  {
    label: "Happy clients",
    labelBn: "সন্তুষ্ট গ্রাহক",
    value: 180,
    prefix: null,
    suffix: "+",
    description: "Commercial buyers, solar contractors, and institutional facilities",
    descriptionBn: "বাণিজ্যিক ক্রেতা, সোলার কন্ট্রাক্টর ও বিভিন্ন প্রতিষ্ঠান",
    sortOrder: 3,
    isActive: true,
    isSample: true,
  },
  {
    label: "Success rate",
    labelBn: "সফলতার হার",
    value: 98,
    prefix: null,
    suffix: "%",
    description: "On-schedule equipment fulfillment and specification accuracy",
    descriptionBn: "সঠিক সময়ে পণ্য সরবরাহ এবং নিখুঁত স্পেসিফিকেশন রক্ষা",
    sortOrder: 4,
    isActive: true,
    isSample: true,
  },
];

export const sampleCertifications = [
  {
    name: "BSREA Certificate of Membership",
    nameBn: "BSREA সদস্যপদ সনদ",
    issuer: "Bangladesh Sustainable & Renewable Energy Association (BSREA)",
    issuerBn: "বাংলাদেশ সাসটেইনেবল অ্যান্ড রিনিউয়েবল এনার্জি অ্যাসোসিয়েশন (BSREA)",
    description: "Official General Membership (20260915GEN113) issued to Tasneem Knitting Industry. Valid through Dec 31, 2026. Document: https://drive.google.com/file/d/1GR4hILXnDjJblqNmrxRNnWH_M7It4Md2/view?usp=sharing",
    descriptionBn: "তাসনিম নিটিং ইন্ডাস্ট্রির অনুকূলে ইস্যুকৃত সাধারণ সদস্যপদ সনদ (20260915GEN113)। ৩১ ডিসেম্বর ২০২৬ পর্যন্ত কার্যকর।",
    image: "/photos/bsrea-logo.png",
    sortOrder: 1,
    isActive: true,
    isSample: true,
  },
  {
    name: "Quality management certificate",
    nameBn: "কোয়ালিটি ম্যানেজমেন্ট সনদ",
    issuer: "Standard Inspection Board",
    issuerBn: "স্ট্যান্ডার্ড ইন্সপেকশন বোর্ড",
    description: "Verified quality management processes for commercial solar equipment distribution",
    descriptionBn: "বাণিজ্যিক সোলার যন্ত্রপাতি আমদানিতে যাচাইকৃত মান নিয়ন্ত্রণ প্রক্রিয়া",
    image: "/demo/cert-quality.svg",
    sortOrder: 2,
    isActive: true,
    isSample: true,
  },
  {
    name: "Product testing certificate",
    nameBn: "পণ্য পরীক্ষণ ও টেস্টিং সনদ",
    issuer: "Accredited Laboratory",
    issuerBn: "স্বীকৃত আন্তর্জাতিক ল্যাবরেটরি",
    description: "Factory electrical performance and laboratory testing verification",
    descriptionBn: "কারখানা পর্যায়ে বৈদ্যুতিক কর্মক্ষমতা ও ল্যাবরেটরি টেস্ট যাচাইকরণ",
    image: "/demo/cert-testing.svg",
    sortOrder: 3,
    isActive: true,
    isSample: true,
  },
  {
    name: "Safety compliance certificate",
    nameBn: "নিরাপত্তা ও কমপ্লায়েন্স সনদ",
    issuer: "Safety Standards Authority",
    issuerBn: "সেফটি স্ট্যান্ডার্ডস অথরিটি",
    description: "Electrical safety, insulation, and dielectric compliance standards",
    descriptionBn: "বৈদ্যুতিক সুরক্ষা, ইনসুলেশন ও ডাই-ইলেকট্রিক মানদণ্ড পূরণ",
    image: "/demo/cert-safety.svg",
    sortOrder: 4,
    isActive: true,
    isSample: true,
  },
  {
    name: "Trade license",
    nameBn: "ট্রেড লাইসেন্স",
    issuer: "Municipal Corporation",
    issuerBn: "সিটি কর্পোরেশন",
    description: "Registered commercial solar equipment import, trade, and supply operations",
    descriptionBn: "সৌর বিদ্যুৎ সামগ্রী আমদানি ও পাইকারি বাণিজ্যের বৈধ নিবন্ধন",
    image: "/demo/cert-license.svg",
    sortOrder: 5,
    isActive: true,
    isSample: true,
  },
];

export const samplePartners = [
  { name: "BSREA", logo: "/photos/bsrea-logo.png", url: "https://bsreabd.org/", sortOrder: 1, isActive: true, isSample: true },
  { name: "Huawei FusionSolar", logo: "/demo/partners/huawei.svg", url: "https://solar.huawei.com", sortOrder: 2, isActive: true, isSample: true },
  { name: "LONGi Solar", logo: "/demo/partners/longi.svg", url: "https://www.longi.com", sortOrder: 2, isActive: true, isSample: true },
  { name: "Sungrow Power", logo: "/demo/partners/sungrow.svg", url: "https://www.sungrowpower.com", sortOrder: 3, isActive: true, isSample: true },
  { name: "JinkoSolar", logo: "/demo/partners/jinko.svg", url: "https://www.jinkosolar.com", sortOrder: 4, isActive: true, isSample: true },
  { name: "Trina Solar", logo: "/demo/partners/trina.svg", url: "https://www.trinasolar.com", sortOrder: 5, isActive: true, isSample: true },
  { name: "JA Solar", logo: "/demo/partners/jasolar.svg", url: "https://www.jasolar.com", sortOrder: 6, isActive: true, isSample: true },
];

export const sampleTestimonials = [
  {
    quote: "“EcoPower helped us seamlessly transition to both solar and wind energy. Our costs have dropped significantly, and we’re now operating more sustainably than ever.”",
    quoteBn: "“নূর সোলার এনার্জির প্যানেল ও ইনভার্টার ব্যবহার করে আমাদের কারখানার বিদ্যুৎ খরচ উল্লেখযোগ্যভাবে কমেছে। পণ্যগুলোর মান চমৎকার এবং ডেলিভারি ছিল একদম সময়মতো।”",
    authorName: "Arif Hossain",
    authorNameBn: "আরিফ হোসেন",
    authorRole: "Business Owner",
    authorRoleBn: "ব্যবস্থাপনা পরিচালক",
    company: "EcoPower",
    companyBn: "ইকোপাওয়ার সলিউশনস",
    photo: "/photos/testimonial-arif.jpg",
    sortOrder: 1,
    isActive: true,
    isSample: true,
  },
  {
    quote: "“The hybrid wind and solar systems installed on our commercial properties cut grid reliance by 65%. Highly recommended team.”",
    quoteBn: "“আমাদের বাণিজ্যিক স্থাপনার জন্য তাদের থেকে হাইব্রিড ইনভার্টার ও লিথিয়াম ব্যাটারি সংগ্রহ করি। গ্রিড বিদ্যুতের উপর নির্ভরতা প্রায় ৬৫% কমে গেছে। তাদের সাপোর্ট সত্যিই প্রশংসনীয়।”",
    authorName: "Mahmud Karim",
    authorNameBn: "মাহমুদ করিম",
    authorRole: "Property Developer",
    authorRoleBn: "প্রকল্প পরিচালক",
    company: "Apex Developments",
    companyBn: "অ্যাপেক্স ডেভেলপমেন্টস",
    photo: "/photos/testimonial-mahmud.jpg",
    sortOrder: 2,
    isActive: true,
    isSample: true,
  },
  {
    quote: "“From initial engineering assessment through commissioning, the experience was flawless. Our production plant achieved ROI faster than projected.”",
    quoteBn: "“ডেটাশিট ও স্পেসিফিকেশন মেলানো থেকে শুরু করে সাইটে ডেলিভারি—পুরো প্রক্রিয়াটি ছিল অত্যন্ত পেশাদার। আমাদের উৎপাদন ইউনিটের প্রত্যাশিত সময়ের আগেই চমৎকার রিটার্ন আসছে।”",
    authorName: "Farhana Ahmed",
    authorNameBn: "ফারহানা আহমেদ",
    authorRole: "Industrial Plant Director",
    authorRoleBn: "প্ল্যান্ট ডিরেক্টর",
    company: "Delta Manufacturing",
    companyBn: "ডেল্টা ম্যানুফ্যাকচারিং",
    photo: "/photos/testimonial-farhana.jpg",
    sortOrder: 3,
    isActive: true,
    isSample: true,
  },
];

export const sampleFaqs = [
  {
    question: "How does the quotation and ordering process work?",
    questionBn: "কোটেশন ও অর্ডার করার প্রক্রিয়া কী?",
    answer: "Submit your product requirements or project specifications through our quote form or via WhatsApp. Our sales engineering team reviews availability, lead time, and commercial pricing, then provides a formal written quotation within business hours.",
    answerBn: "আমাদের কোটেশন ফরম বা সরাসরি হোয়াটসঅ্যাপের মাধ্যমে আপনার পণ্যের তালিকা ও পরিমাণ জানান। আমাদের টিম স্টক, ডেলিভারির সময় এবং পাইকারি দর যাচাই করে অফিস চলাকালীন সময়েই আনুষ্ঠানিক লিখিত কোটেশন পাঠিয়ে দেবে।",
    sortOrder: 1,
    isActive: true,
    isSample: true,
  },
  {
    question: "What is the minimum order quantity (MOQ)?",
    questionBn: "ন্যূনতম অর্ডার পরিমাণ (MOQ) কত?",
    answer: "MOQ varies by product category and model. Many core inverter and battery models can be ordered as single units, while select modules require minimum pallet quantities. Contact our sales team for current terms on specific items.",
    answerBn: "পণ্যের ধরন ও মডেল অনুযায়ী MOQ নির্ধারিত হয়। বেশিরভাগ ইনভার্টার ও লিথিয়াম ব্যাটারি ১টি ইউনিট থেকেই অর্ডার করা যায়। সোলার প্যানেলের ক্ষেত্রে সাধারণত পূর্ণ প্যালেট অর্ডারের প্রয়োজন হয়। নির্দিষ্ট পণ্যের বর্তমান শর্ত জানতে আমাদের সেলস টিমের সাথে যোগাযোগ করুন।",
    sortOrder: 2,
    isActive: true,
    isSample: true,
  },
  {
    question: "Are product datasheets and test reports available?",
    questionBn: "পণ্যের ডেটাশিট ও টেস্ট রিপোর্ট কি পাওয়া যাবে?",
    answer: "Complete manufacturer datasheets, technical specifications, and laboratory test documentation are available for all catalog models upon request from our engineering desk.",
    answerBn: "হ্যাঁ, আমাদের সব মডেলের অফিসিয়াল প্রস্তুতকারক ডেটাশিট, কারিগরি স্পেসিফিকেশন এবং ল্যাবরেটরি টেস্ট রিপোর্ট সংরক্ষিত আছে। অনুরোধ করলেই আমাদের ইঞ্জিনিয়ারিং ডেস্ক থেকে এগুলো সরবরাহ করা হয়।",
    sortOrder: 3,
    isActive: true,
    isSample: true,
  },
  {
    question: "What delivery and logistics options do you offer across Bangladesh?",
    questionBn: "সারা বাংলাদেশে ডেলিভারি ও পরিবহন ব্যবস্থা কেমন?",
    answer: "We coordinate transport logistics for commercial deliveries nationwide, including warehouse pickup, regional freight dispatch, and scheduled project site drops. Contact our logistics desk for scheduling.",
    answerBn: "সারা দেশের যেকোনো প্রান্তে বাণিজ্যিক ডেলিভারির জন্য আমরা নির্ভরযোগ্য পরিবহন সুবিধা সমন্বয় করি। ওয়্যারহাউস থেকে সরাসরি পিকআপ বা প্রকল্প সাইটে সরাসরি ট্রাক ডেলিভারি—উভয় সুবিধাই রয়েছে। বিস্তারিত জানতে আমাদের লজিস্টিকস ডেস্কে কথা বলুন।",
    sortOrder: 4,
    isActive: true,
    isSample: true,
  },
  {
    question: "What payment terms are accepted for commercial orders?",
    questionBn: "বাণিজ্যিক অর্ডারের ক্ষেত্রে পেমেন্ট মাধ্যম কী কী?",
    answer: "We accept standard commercial bank transfers, verified pay orders, and company cheques according to agreed quotation milestones. Contact our sales team for current credit and settlement terms.",
    answerBn: "আমরা নির্ধারিত কোটেশন শর্ত অনুযায়ী বাণিজ্যিক ব্যাংক ট্রান্সফার (BEFTN/RTGS), পে-অর্ডার এবং অ্যাকাউন্ট পেয়ী চেক গ্রহণ করি। পেমেন্টের বিস্তারিত শর্তাবলি জানতে আমাদের সেলস টিমের সাথে যোগাযোগ করুন।",
    sortOrder: 5,
    isActive: true,
    isSample: true,
  },
  {
    question: "What after-sales and technical support do you provide?",
    questionBn: "বিক্রয়োত্তর সেবা ও কারিগরি সহায়তা কীভাবে দেওয়া হয়?",
    answer: "Our technical team assists with pre-installation specification verification, commissioning guidance, and manufacturer warranty claim coordination. Contact our support desk for active project assistance.",
    answerBn: "আমাদের কারিগরি দল প্রজেক্ট শুরুর আগে স্পেসিফিকেশন মিলিয়ে দেখা, কমিশনিং পরামর্শ এবং প্রস্তুতকারক কোম্পানির ওয়ারেন্টি সংক্রান্ত সমন্বয়ে পূর্ণ সহায়তা প্রদান করে। যেকোনো প্রয়োজনে আমাদের টেকনিক্যাল ডেস্কে যোগাযোগ করতে পারেন।",
    sortOrder: 6,
    isActive: true,
    isSample: true,
  },
];
