export const sampleStats = [
  {
    label: "Years in business",
    value: 8,
    prefix: null,
    suffix: "+",
    description: "Established presence supplying commercial installations across Bangladesh",
    sortOrder: 1,
    isActive: true,
    isSample: true,
  },
  {
    label: "Projects supplied",
    value: 250,
    prefix: null,
    suffix: "+",
    description: "Industrial rooftops, commercial facilities, and rural telecom setups",
    sortOrder: 2,
    isActive: true,
    isSample: true,
  },
  {
    label: "Happy clients",
    value: 180,
    prefix: null,
    suffix: "+",
    description: "Commercial buyers, solar contractors, and institutional facilities",
    sortOrder: 3,
    isActive: true,
    isSample: true,
  },
  {
    label: "Success rate",
    value: 98,
    prefix: null,
    suffix: "%",
    description: "On-schedule equipment fulfillment and specification accuracy",
    sortOrder: 4,
    isActive: true,
    isSample: true,
  },
];

export const sampleCertifications = [
  {
    name: "Quality management certificate",
    issuer: "Standard Inspection Board",
    description: "Verified quality management processes for commercial solar equipment distribution",
    image: "/demo/cert-quality.svg",
    sortOrder: 1,
    isActive: true,
    isSample: true,
  },
  {
    name: "Product testing certificate",
    issuer: "Accredited Laboratory",
    description: "Factory electrical performance and laboratory testing verification",
    image: "/demo/cert-testing.svg",
    sortOrder: 2,
    isActive: true,
    isSample: true,
  },
  {
    name: "Safety compliance certificate",
    issuer: "Safety Standards Authority",
    description: "Electrical safety, insulation, and dielectric compliance standards",
    image: "/demo/cert-safety.svg",
    sortOrder: 3,
    isActive: true,
    isSample: true,
  },
  {
    name: "Trade license",
    issuer: "Municipal Corporation",
    description: "Registered commercial solar equipment import, trade, and supply operations",
    image: "/demo/cert-license.svg",
    sortOrder: 4,
    isActive: true,
    isSample: true,
  },
];

export const samplePartners = [
  { name: "Huawei FusionSolar", logo: "/demo/partners/huawei.svg", url: "https://solar.huawei.com", sortOrder: 1, isActive: true, isSample: true },
  { name: "LONGi Solar", logo: "/demo/partners/longi.svg", url: "https://www.longi.com", sortOrder: 2, isActive: true, isSample: true },
  { name: "Sungrow Power", logo: "/demo/partners/sungrow.svg", url: "https://www.sungrowpower.com", sortOrder: 3, isActive: true, isSample: true },
  { name: "JinkoSolar", logo: "/demo/partners/jinko.svg", url: "https://www.jinkosolar.com", sortOrder: 4, isActive: true, isSample: true },
  { name: "Trina Solar", logo: "/demo/partners/trina.svg", url: "https://www.trinasolar.com", sortOrder: 5, isActive: true, isSample: true },
  { name: "JA Solar", logo: "/demo/partners/jasolar.svg", url: "https://www.jasolar.com", sortOrder: 6, isActive: true, isSample: true },
];

export const sampleTestimonials = [
  {
    quote: "“EcoPower helped us seamlessly transition to both solar and wind energy. Our costs have dropped significantly, and we’re now operating more sustainably than ever.”",
    authorName: "Arif Hossain",
    authorRole: "Business Owner",
    company: "EcoPower",
    photo: "/photos/testimonial-arif.jpg",
    sortOrder: 1,
    isActive: true,
    isSample: true,
  },
  {
    quote: "“The hybrid wind and solar systems installed on our commercial properties cut grid reliance by 65%. Highly recommended team.”",
    authorName: "Mahmud Karim",
    authorRole: "Property Developer",
    company: "Apex Developments",
    photo: "/photos/testimonial-mahmud.jpg",
    sortOrder: 2,
    isActive: true,
    isSample: true,
  },
  {
    quote: "“From initial engineering assessment through commissioning, the experience was flawless. Our production plant achieved ROI faster than projected.”",
    authorName: "Farhana Ahmed",
    authorRole: "Industrial Plant Director",
    company: "Delta Manufacturing",
    photo: "/photos/testimonial-farhana.jpg",
    sortOrder: 3,
    isActive: true,
    isSample: true,
  },
];

export const sampleFaqs = [
  {
    question: "How does the quotation and ordering process work?",
    answer: "Submit your product requirements or project specifications through our quote form or via WhatsApp. Our sales engineering team reviews availability, lead time, and commercial pricing, then provides a formal written quotation within business hours.",
    sortOrder: 1,
    isActive: true,
    isSample: true,
  },
  {
    question: "What is the minimum order quantity (MOQ)?",
    answer: "MOQ varies by product category and model. Many core inverter and battery models can be ordered as single units, while select modules require minimum pallet quantities. Contact our sales team for current terms on specific items.",
    sortOrder: 2,
    isActive: true,
    isSample: true,
  },
  {
    question: "Are product datasheets and test reports available?",
    answer: "Complete manufacturer datasheets, technical specifications, and laboratory test documentation are available for all catalog models upon request from our engineering desk.",
    sortOrder: 3,
    isActive: true,
    isSample: true,
  },
  {
    question: "What delivery and logistics options do you offer across Bangladesh?",
    answer: "We coordinate transport logistics for commercial deliveries nationwide, including warehouse pickup, regional freight dispatch, and scheduled project site drops. Contact our logistics desk for scheduling.",
    sortOrder: 4,
    isActive: true,
    isSample: true,
  },
  {
    question: "What payment terms are accepted for commercial orders?",
    answer: "We accept standard commercial bank transfers, verified pay orders, and company cheques according to agreed quotation milestones. Contact our sales team for current credit and settlement terms.",
    sortOrder: 5,
    isActive: true,
    isSample: true,
  },
  {
    question: "What after-sales and technical support do you provide?",
    answer: "Our technical team assists with pre-installation specification verification, commissioning guidance, and manufacturer warranty claim coordination. Contact our support desk for active project assistance.",
    sortOrder: 6,
    isActive: true,
    isSample: true,
  },
];
